global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'cluster']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'email'

receivers:
  - name: 'email'
    email_configs:
      - to: 'ashutoshp.dev@gmail.com' # Specify your Gmail address here
        from: 'ashutoshpanda575@gmail.com' # Specify the sender Gmail address
        smarthost: 'smtp.gmail.com:587' # Gmail SMTP server and port
        auth_username: 'ashutoshpanda575@gmail.com' # Your Gmail address for authentication
        auth_password: 'oisk qmtb emgg ennp' # Your Gmail password
        auth_identity: 'ashutoshpanda575@gmail.com' # Specify the identity
        require_tls: true # Require TLS encryption
