global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus-instance'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'prometheus-app-server'
    # scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'prometheus-mongodb'
    # scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:9216']

  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323'] # Docker daemon metrics endpoint

rule_files:
  - alert.rules.yml # Load alerting rules from separate file
